//
// bas.c - "Run .bas": a BASIC program from a text file on the card,
// put into the machine's memory as if it had been typed.
//
// The ROM's BASIC keeps a program at 4001h as lines of {link to the
// next line (2 bytes, absolute), line number (2), the text with the
// keywords and operators as one-byte tokens and everything else as
// typed, in capitals, 0}, then a 00 00 link; and four pointers at
// F92Eh: TXTTAB (4001h), VARTAB, ARYTAB, STREND - the three of them at
// the end of the program when no variables exist.  Numbers are not
// encoded (a RAM dump of a typed line showed the digits as text), so
// tokenising is: keywords and operators to their bytes, letters outside
// a string to capitals, a REM's text and a string verbatim.  The token
// table is the ROM's own (pk8000_tokens.h, generated by tools/mkcas.py
// from tang/rom/pk8000_v12.rom); tools/mkcas.py writes the same bytes
// into a .cas, and the two must agree.
//
// The text file is UTF-8.  The machine's character set is КОИ-8: the
// ROM's banner spells "версия" as D7 C5 D2 D3 C9 D1 and "ПК" as F0 EB
// (1762h), the KOI8-R letters (а..я at C0h-DFh in that table's order,
// А..Я 20h above).  A Cyrillic letter is turned into that byte wherever
// it stands; Ё/ё (KOI8-R B3h/A3h, not known to be in the Сура's font),
// any other character above 7Fh and a broken UTF-8 sequence become '*'.
// A byte-order mark at the start of a line is dropped.
//
// The FPGA side is sysctrl.v's CMD 6 (an address, then bytes) and
// poke.v, which writes them into the SDRAM in T-states the CPU leaves
// free.  So: reset the machine, wait for BASIC's prompt, send the lines
// one by one to their addresses, send the pointers, then type "run" and
// Enter through the keyboard path (usb_host.c's kbd_tx codes).
//
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "bas.h"
#include "pk8000_tokens.h"

#define BAS_TXTTAB   0x4001
#define BAS_PTRS     0xF930    // VARTAB, ARYTAB, STREND
#define BAS_MAXLINE  250       // bytes of one tokenised line

// the 32 lowercase letters а..я (U+0430..U+044F) in KOI8-R
static const unsigned char koi8_lower[32] = {
  0xC1, 0xC2, 0xD7, 0xC7, 0xC4, 0xC5, 0xD6, 0xDA,   // а б в г д е ж з
  0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0,   // и й к л м н о п
  0xD2, 0xD3, 0xD4, 0xD5, 0xC6, 0xC8, 0xC3, 0xDE,   // р с т у ф х ц ч
  0xDB, 0xDD, 0xDF, 0xD9, 0xD8, 0xDC, 0xC0, 0xD1 }; // ш щ ъ ы ь э ю я

// One UTF-8 sequence at *text into the machine's byte; advances the
// pointer past it.  ASCII is itself; Cyrillic is KOI-8; the rest is '*'.
static unsigned char bas_char(const char **text) {
  const unsigned char *p = (const unsigned char *)*text;
  unsigned c = p[0];
  int len = 1;
  if(c < 0x80) { (*text)++; return c; }
  // the code point, if the sequence is well formed
  unsigned cp = 0;
  if((c & 0xE0) == 0xC0) { cp = c & 0x1F; len = 2; }
  else if((c & 0xF0) == 0xE0) { cp = c & 0x0F; len = 3; }
  else if((c & 0xF8) == 0xF0) { cp = c & 0x07; len = 4; }
  else { (*text)++; return '*'; }              // a stray continuation byte
  for(int i = 1; i < len; i++) {
    if((p[i] & 0xC0) != 0x80) { *text += i; return '*'; }   // cut short
    cp = (cp << 6) | (p[i] & 0x3F);
  }
  *text += len;
  if(cp >= 0x0430 && cp <= 0x044F) return koi8_lower[cp - 0x0430];
  if(cp >= 0x0410 && cp <= 0x042F) return koi8_lower[cp - 0x0410] + 0x20;
  return '*';
}

// One line of text into its tokenised form (without the link, the
// number and the terminating zero).  Returns the length, or -1 if the
// line does not start with a number.
int bas_tokenise(const char *text, unsigned char *out, int max, unsigned *number) {
  if(!strncmp(text, "\xEF\xBB\xBF", 3)) text += 3;     // a UTF-8 byte-order mark
  while(*text == ' ' || *text == '\t') text++;
  if(!isdigit((unsigned char)*text)) return -1;
  *number = 0;
  while(isdigit((unsigned char)*text)) *number = *number * 10 + (*text++ - '0');
  while(*text == ' ') text++;

  int n = 0;
  int verbatim = 0;       // after REM or '
  int in_string = 0;
  while(*text && *text != '\r' && *text != '\n') {
    if(n >= max - 1) return n;
    if(verbatim) { out[n++] = bas_char(&text); continue; }
    if(in_string) {
      if(*text == '"') in_string = 0;
      out[n++] = bas_char(&text);
      continue;
    }
    if(*text == '"') { in_string = 1; out[n++] = *text++; continue; }
    if((unsigned char)*text >= 0x80) { out[n++] = bas_char(&text); continue; }   // Cyrillic outside a string: as it is

    // the longest keyword or operator here (the table is longest-first)
    const char *best = NULL; unsigned char token = 0;
    for(int i = 0; pk8000_tokens[i].word; i++) {
      const char *w = pk8000_tokens[i].word;
      int l = strlen(w), k;
      for(k = 0; k < l; k++)
        if(toupper((unsigned char)text[k]) != w[k]) break;
      if(k == l) { best = w; token = pk8000_tokens[i].token; break; }
    }
    if(best) {
      out[n++] = token;
      text += strlen(best);
      if(!strcmp(best, "REM") || !strcmp(best, "'")) verbatim = 1;
      continue;
    }
    out[n++] = toupper((unsigned char)*text);
    text++;
  }
  return n;
}

#ifndef BAS_HOST_TEST

#include "ff.h"
#include "sdc.h"
#include "sysctrl.h"
#include "FreeRTOS.h"
#include "task.h"

extern void kbd_tx(spi_t *spi, unsigned char byte);

// a key press and release, held long enough for the ROM's once-a-frame scan
static void bas_key(spi_t *spi, unsigned char code) {
  kbd_tx(spi, code);
  vTaskDelay(pdMS_TO_TICKS(60));
  kbd_tx(spi, 0x80 | code);
  vTaskDelay(pdMS_TO_TICKS(60));
}

static void bas_poke_begin(spi_t *spi, unsigned addr) {
  spi_begin(spi);
  spi_tx_u08(spi, SPI_TARGET_SYS);
  spi_tx_u08(spi, SPI_SYS_POKE);
  spi_tx_u08(spi, addr >> 8);
  spi_tx_u08(spi, addr & 0xff);
}

int bas_run(spi_t *spi, const char *path) {
  FIL file;
  static unsigned char line[BAS_MAXLINE + 5];
  static char text[256];

  sdc_lock();
  if(f_open(&file, path, FA_OPEN_EXISTING | FA_READ) != FR_OK) {
    sdc_unlock();
    printf("bas: cannot open %s\r\n", path);
    return -1;
  }

  // the machine to its prompt: BASIC's initialisation takes about two
  // seconds after a reset (progress.md's boot log)
  sys_set_val(spi, 'R', 1);
  sys_set_val(spi, 'R', 0);
  vTaskDelay(pdMS_TO_TICKS(3000));

  unsigned addr = BAS_TXTTAB;
  int lines = 0;
  while(f_gets(text, sizeof(text), &file)) {
    unsigned number;
    int n = bas_tokenise(text, line + 4, BAS_MAXLINE, &number);
    if(n < 0) continue;                   // not a program line
    unsigned next = addr + 4 + n + 1;
    line[0] = next & 0xff; line[1] = next >> 8;
    line[2] = number & 0xff; line[3] = number >> 8;
    line[4 + n] = 0;
    bas_poke_begin(spi, addr);
    for(int i = 0; i < 4 + n + 1; i++) spi_tx_u08(spi, line[i]);
    spi_end(spi);
    addr = next;
    lines++;
  }
  f_close(&file);
  sdc_unlock();

  // the end of the program and the three pointers to it
  unsigned end = addr + 2;
  bas_poke_begin(spi, addr);
  spi_tx_u08(spi, 0); spi_tx_u08(spi, 0);
  spi_end(spi);
  bas_poke_begin(spi, BAS_PTRS);
  for(int i = 0; i < 3; i++) { spi_tx_u08(spi, end & 0xff); spi_tx_u08(spi, end >> 8); }
  spi_end(spi);
  printf("bas: %d lines, %u bytes at 4001h\r\n", lines, end - BAS_TXTTAB);

  // r u n Enter: row*8 + col + 1 (pk8000.h)
  vTaskDelay(pdMS_TO_TICKS(50));
  bas_key(spi, 4*8 + 7 + 1);
  bas_key(spi, 5*8 + 2 + 1);
  bas_key(spi, 4*8 + 3 + 1);
  bas_key(spi, 7*8 + 7 + 1);
  return 0;
}

#endif
